# Libs

In [1]:
import pandas as pd
import requests
import os
import warnings
import time
warnings.filterwarnings('ignore')

URL = "https://dadosabertos.camara.leg.br/api/v2/"

/Users/falcone/Desktop/Projects/CD-2025-2/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

# GET Data

## GET Deputados Infos

In [ ]:
# Lista todos os deputados em exercício
deputados = requests.get(f"{URL}deputados").json()["dados"]
df_deputados = pd.DataFrame(deputados)

# Recupera mais informações de cada deputado por id
detalhes = []
for id in df_deputados['id']:
    info = requests.get(f"{URL}deputados/{id}").json()["dados"]
    detalhes.append(info)
    time.sleep(0.5)  # Para evitar sobrecarga no servidor

df_detalhes = pd.DataFrame(detalhes)
df_deputados = df_deputados.merge(df_detalhes, how='left', on='id', suffixes=('', '_y'))

df_deputados.drop(columns=["uri_y"], inplace=True)
df_deputados

,id,uri,nome,siglaPartido,uriPartido,siglaUf,idLegislatura,urlFoto,email,uri_y,...,ultimoStatus,cpf,sexo,urlWebsite,redeSocial,dataNascimento,dataFalecimento,ufNascimento,municipioNascimento,escolaridade
0,204379,https://dadosabertos.camara.leg.br/api/v2/depu...,Acácio Favacho,MDB,https://dadosabertos.camara.leg.br/api/v2/part...,AP,57,https://www.camara.leg.br/internet/deputado/ba...,dep.acaciofavacho@camara.leg.br,https://dadosabertos.camara.leg.br/api/v2/depu...,...,"{'id': 204379, 'uri': 'https://dadosabertos.ca...",74287028287,M,None,"[https://twitter.com/acaciofavacho, https://ww...",1983-09-28,None,AP,Macapá,Superior
1,220714,https://dadosabertos.camara.leg.br/api/v2/depu...,Adail Filho,REPUBLICANOS,https://dadosabertos.camara.leg.br/api/v2/part...,AM,57,https://www.camara.leg.br/internet/deputado/ba...,dep.adailfilho@camara.leg.br,https://dadosabertos.camara.leg.br/api/v2/depu...,...,"{'id': 220714, 'uri': 'https://dadosabertos.ca...",77267796249,M,None,[https://twitter.com/adailfilhoam?s=21&t=O_eoT...,1992-02-16,None,AM,Manaus,Superior Incompleto
2,221328,https://dadosabertos.camara.leg.br/api/v2/depu...,Adilson Barroso,PL,https://dadosabertos.camara.leg.br/api/v2/part...,SP,57,https://www.camara.leg.br/internet/deputado/ba...,dep.adilsonbarroso@camara.leg.br,https://dadosabertos.camara.leg.br/api/v2/depu...,...,"{'id': 221328, 'uri': 'https://dadosabertos.ca...",05585378805,M,None,[],1964-06-14,None,MG,Minas Novas,Superior
3,204560,https://dadosabertos.camara.leg.br/api/v2/depu...,Adolfo Viana,PSDB,https://dadosabertos.camara.leg.br/api/v2/part...,BA,57,https://www.camara.leg.br/internet/deputado/ba...,dep.adolfoviana@camara.leg.br,https://dadosabertos.camara.leg.br/api/v2/depu...,...,"{'id': 204560, 'uri': 'https://dadosabertos.ca...",80123848504,M,None,[],1981-02-02,None,BA,Salvador,Superior
4,204528,https://dadosabertos.camara.leg.br/api/v2/depu...,Adriana Ventura,NOVO,https://dadosabertos.camara.leg.br/api/v2/part...,SP,57,https://www.camara.leg.br/internet/deputado/ba...,dep.adrianaventura@camara.leg.br,https://dadosabertos.camara.leg.br/api/v2/depu...,...,"{'id': 204528, 'uri': 'https://dadosabertos.ca...",12519851813,F,None,"[https://twitter.com/adriventurasp, https://ww...",1969-03-06,None,SP,São Paulo,Doutorado

## GET despesas por deputado

In [10]:
# Recupera mais informações de cada deputado por id
despesas = []
for id in df_deputados['id']:
    info = requests.get(f"{URL}deputados/{id}/despesas").json()["dados"]
    despesas.append(info)
    time.sleep(0.5)  # Para evitar sobrecarga no servidor
df_despesas = pd.DataFrame(despesas)
df_despesas

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'COMBUS..."
1,"{'ano': 2025, 'mes': 4, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'COMBUS..."
2,"{'ano': 2025, 'mes': 4, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'COMBUS..."
3,"{'ano': 2025, 'mes': 4, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'COMBUS..."
4,"{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
507,"{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'MANUTE..."
508,"{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'COMBUS..."
509,"{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE..."
510,"{'ano': 2025, 'mes': 10, 'tipoDespesa': 'MANUT...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 10, 'tipoDespesa': 'COMBU...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'COMBUS...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'COMBUS..."
511,"{'ano': 2025, 'mes': 4, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 8, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 9, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 4, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 5, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 6, 'tipoDespesa': 'MANUTE...","{'ano': 2025, 'mes': 7, 'tipoDespesa': 'MANUTE..."